/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;


import DB.DB;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.TableRowSorter;

/**
 *
 * @author jorge
 */
public class Busqueda extends javax.swing.JFrame {

    private TableRowSorter trsfiltro;

    /**
     * Creates new form Busqueda
     */
    public Busqueda() {
        initComponents();
        Modelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblPalabra = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        lblPalabra.setText("Palabra a Buscar:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Palabra", "Apariciones", "Documentos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPalabra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 194, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPalabra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        jTextField1.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (jTextField1.getText());
                cadena = cadena.toLowerCase();
                jTextField1.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsfiltro = new TableRowSorter(jTable1.getModel());
        jTable1.setRowSorter(trsfiltro);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
            // TODO add your handling code here:
            Obtener_Datos();
        
          

    }//GEN-LAST:event_formWindowOpened

    public static DefaultTableModel Modelo_Tabla;

    public void Obtener_Datos() {
        try {
            int i = 0;
            Object row[] = null;
            DB BD = new DB();
            BD.ConectarBD();
            String consulta;
            consulta="SELECT palabra as Palabra, count(*) AS Archivos, sum(frecuencia) AS Frecuencia  "
                    + "FROM SUPERTABLA"
                    + "GROUP BY Palabra";
            BD.resultado = BD.sentencia.executeQuery(consulta);
            if (BD.resultado != null) {
                
                    while (BD.resultado.next()) {
                        Modelo_Tabla.addRow(row);
                        Modelo_Tabla.setValueAt(BD.resultado.getString("Nombre"), i, 0);
                    Modelo_Tabla.setValueAt(BD.resultado.getString("Frecuencia"), i, 1);
                        Modelo_Tabla.setValueAt(BD.resultado.getString("Archivos"), i, 2);
                        i++;
                    }

                }
        }
       catch (Exception e) {
           JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

//    public String crearTabla(){
//
//            String consulta="";
//            consulta= "  CREATE TABLE Palabra"
//                    + " ("
//                    + " id_palabra INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)"
//                    + ", nombre VARCHAR(25) NOT NULL"
//                    + ", CONSTRAINT nombre_Un"
//                    + " UNIQUE (nombre)"
//                    + "); "
//                    + " CREATE TABLE  Archivo"
//                    + "("
//                    + " id_archivo INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)"
//                    + ", nombre VARCHAR(25) NOT NULL"
//                    + ", CONSTRAINT nombre_UQ"
//                    + " UNIQUE (nombre)"
//                    + " ); "
//                    + "CREATE TABLE Diccionario "
//                    + "("
//                    + " id_diccionario  INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1)"
//                    + ", nombre VARCHAR(25)"
//                    + ", fecha TIMESTAMP NOT NULL "
//                    + "); "
//                    + "CREATE TABLE  ArchivoXPalabra "
//                    + "("
//                    + " id_archivo INT NOT NULL"
//                    + ", id_palabra INT NOT NULL"
//                    + ", frecuencia INT NOT NULL"
//                    + ", PRIMARY KEY (id_archivo, id_palabra)"
//                    + ", CONSTRAINT archivo_FK"
//                    + " FOREIGN KEY (id_archivo)"
//                    + " REFERENCES Archivo (id_archivo)"
//                    + ", CONSTRAINT palabra_FK"
//                    + " FOREIGN KEY (id_palabra)"
//                    + " REFERENCES Palabra (id_palabra)"
//                    + "); "
//                    + "CREATE TABLE  ArchivoXPalabraXDiccionario "
//                    + "("
//                    + " id_archivo INT NOT NULL"
//                    + ", id_palabra INT NOT NULL"
//                    + ", id_diccionario INT NOT NULL"
//                    + ", PRIMARY KEY (id_archivo, id_palabra, id_diccionario)"
//                    + ", CONSTRAINT juntar_FK"
//                    + " FOREIGN KEY (id_archivo, id_palabra)"
//                    + " REFERENCES ArchivoXPalabra (id_archivo, id_palabra)"
//                    + ", CONSTRAINT dicc_FK"
//                    + " FOREIGN KEY (id_diccionario)"
//                    + " REFERENCES Diccionario (id_diccionario)"
//                    + ")";
//            System.out.println(consulta);
//            
//            return consulta;
//    }
    private void Modelo() {
        try {
            Modelo_Tabla = (new DefaultTableModel(
                    null, new String[]{"Palabra", "Frecuencia", "Archivos"}) {
                        Class[] types = new Class[]{
                            java.lang.String.class,
                            java.lang.String.class,
                         java.lang.String.class,
                        };
                        boolean[] canEdit = new boolean[]{
                            false, false, false
                        };

                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types[columnIndex];
                        }

                        @Override
                        public boolean isCellEditable(int rowIndex, int colIndex) {
                            return canEdit[colIndex];
                        }
                    });
            jTable1.setModel(Modelo_Tabla);
            jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            jTable1.getTableHeader().setReorderingAllowed(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + " error");
        }
    }

    public void filtro() {
        trsfiltro.setRowFilter(RowFilter.regexFilter("^" + jTextField1.getText(), 0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPalabra;
    // End of variables declaration//GEN-END:variables
}
